package com.crx.raf.kids.d1.util;

public enum  ErrorCode {
    URL_PARSING_ERROR,
    CRAWLER_ERROR,
    JOB_ERROR,
    RESULTS_ARE_NOT_AVAILABLE_YET,
    THERE_ARE_NO_STARTED_JOBS,
    RESULT_RETRIEVER_SUMMARY_ERROR,
    WEB_URL_VISITED
}
